feat: 🎸 adds support for active button on buttonbar component
eVisit/react-ameliorate pull request #16
Opened 2020-11-05 14:20 UTC by arctouch-marcomafessolli

2020-11-05 18:22 UTC, 99ff00 approved these changes

2020-11-06 18:53 UTC, RyanWiltbank approved these changes

2020-11-06 18:55 UTC, haly88 approved these changes

2020-11-06 19:41 UTC, th317erd requested changes

2020-11-06 19:41 UTC, th317erd commented on packages/react-ameliorate-component-button-bar/source/button-bar.js
> +          lastPressedButton: null
Last please change this to be an index instead
```suggestion
          activeButtonIndex: null
```

2020-11-06 21:32 UTC, th317erd approved these changes

2020-11-06 21:33 UTC, merged